safe: false
markdown: rdiscount
pygments: true
exclude: ["legacy-imports", "Rakefile", "README.md", "_template.md", "new.rb", "add-filenames-to-posts.sh"]
multivews: true


rdiscount:
    extensions: [smart]

